"""Add Milestone 2A funding_opportunities and funding_keywords tables

Revision ID: f8e9f392e6c3
Revises: 626ab1f43993
Create Date: 2026-08-25 01:01:45.265121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e9f392e6c3'
down_revision: Union[str, None] = '626ab1f43993'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funding_opportunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('funding_agency', sa.String(length=255), nullable=False),
    sa.Column('funding_program', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('funding_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opportunity_type', sa.String(length=100), nullable=True),
    sa.Column('eligibility_summary', sa.Text(), nullable=True),
    sa.Column('eligible_institutions', sa.String(length=255), nullable=True),
    sa.Column('geographic_restrictions', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_opportunities_application_deadline'), 'funding_opportunities', ['application_deadline'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_created_by_user_id'), 'funding_opportunities', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_external_id'), 'funding_opportunities', ['external_id'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_funding_agency'), 'funding_opportunities', ['funding_agency'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_funding_amount'), 'funding_opportunities', ['funding_amount'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_funding_program'), 'funding_opportunities', ['funding_program'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_id'), 'funding_opportunities', ['id'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_opportunity_type'), 'funding_opportunities', ['opportunity_type'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_source'), 'funding_opportunities', ['source'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_status'), 'funding_opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_funding_opportunities_title'), 'funding_opportunities', ['title'], unique=False)
    op.create_table('funding_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('funding_opportunity_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['funding_opportunity_id'], ['funding_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funding_keywords_funding_opportunity_id'), 'funding_keywords', ['funding_opportunity_id'], unique=False)
    op.create_index(op.f('ix_funding_keywords_id'), 'funding_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_funding_keywords_keyword'), 'funding_keywords', ['keyword'], unique=False)
    op.create_table('funding_opportunity_domains',
    sa.Column('funding_opportunity_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['research_domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['funding_opportunity_id'], ['funding_opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('funding_opportunity_id', 'domain_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funding_opportunity_domains')
    op.drop_index(op.f('ix_funding_keywords_keyword'), table_name='funding_keywords')
    op.drop_index(op.f('ix_funding_keywords_id'), table_name='funding_keywords')
    op.drop_index(op.f('ix_funding_keywords_funding_opportunity_id'), table_name='funding_keywords')
    op.drop_table('funding_keywords')
    op.drop_index(op.f('ix_funding_opportunities_title'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_status'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_source'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_opportunity_type'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_id'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_funding_program'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_funding_amount'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_funding_agency'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_external_id'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_created_by_user_id'), table_name='funding_opportunities')
    op.drop_index(op.f('ix_funding_opportunities_application_deadline'), table_name='funding_opportunities')
    op.drop_table('funding_opportunities')
    # ### end Alembic commands ###
