"""Add Phase 2E patents and profile_patents tables

Revision ID: 626ab1f43993
Revises: 53d7c57aa26c
Create Date: 2026-08-25 00:55:35.087943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '626ab1f43993'
down_revision: Union[str, None] = '53d7c57aa26c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patent_number', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('inventors', sa.Text(), nullable=True),
    sa.Column('filing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patent_classification', sa.String(length=100), nullable=True),
    sa.Column('technology_domain', sa.String(length=150), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patents_assignee'), 'patents', ['assignee'], unique=False)
    op.create_index(op.f('ix_patents_citation_count'), 'patents', ['citation_count'], unique=False)
    op.create_index(op.f('ix_patents_external_id'), 'patents', ['external_id'], unique=False)
    op.create_index(op.f('ix_patents_filing_date'), 'patents', ['filing_date'], unique=False)
    op.create_index(op.f('ix_patents_id'), 'patents', ['id'], unique=False)
    op.create_index(op.f('ix_patents_patent_classification'), 'patents', ['patent_classification'], unique=False)
    op.create_index(op.f('ix_patents_patent_number'), 'patents', ['patent_number'], unique=True)
    op.create_index(op.f('ix_patents_publication_date'), 'patents', ['publication_date'], unique=False)
    op.create_index(op.f('ix_patents_source'), 'patents', ['source'], unique=False)
    op.create_index(op.f('ix_patents_technology_domain'), 'patents', ['technology_domain'], unique=False)
    op.create_index(op.f('ix_patents_title'), 'patents', ['title'], unique=False)
    op.create_table('profile_patents',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('patent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patent_id'], ['patents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'patent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_patents')
    op.drop_index(op.f('ix_patents_title'), table_name='patents')
    op.drop_index(op.f('ix_patents_technology_domain'), table_name='patents')
    op.drop_index(op.f('ix_patents_source'), table_name='patents')
    op.drop_index(op.f('ix_patents_publication_date'), table_name='patents')
    op.drop_index(op.f('ix_patents_patent_number'), table_name='patents')
    op.drop_index(op.f('ix_patents_patent_classification'), table_name='patents')
    op.drop_index(op.f('ix_patents_id'), table_name='patents')
    op.drop_index(op.f('ix_patents_filing_date'), table_name='patents')
    op.drop_index(op.f('ix_patents_external_id'), table_name='patents')
    op.drop_index(op.f('ix_patents_citation_count'), table_name='patents')
    op.drop_index(op.f('ix_patents_assignee'), table_name='patents')
    op.drop_table('patents')
    # ### end Alembic commands ###
