"""Add Phase 2A normalized research profile tables

Revision ID: 68afbe48340e
Revises: 706d13f3e174
Create Date: 2026-08-25 00:33:27.963388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68afbe48340e'
down_revision: Union[str, None] = '706d13f3e174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_domains_id'), 'research_domains', ['id'], unique=False)
    op.create_index(op.f('ix_research_domains_name'), 'research_domains', ['name'], unique=True)
    op.create_table('academic_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=False),
    sa.Column('field_of_study', sa.String(length=150), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_histories_id'), 'academic_histories', ['id'], unique=False)
    op.create_index(op.f('ix_academic_histories_profile_id'), 'academic_histories', ['profile_id'], unique=False)
    op.create_table('profile_domains',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['research_domains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'domain_id')
    )
    op.create_table('profile_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_keywords_id'), 'profile_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_profile_keywords_keyword'), 'profile_keywords', ['keyword'], unique=False)
    op.create_index(op.f('ix_profile_keywords_profile_id'), 'profile_keywords', ['profile_id'], unique=False)
    op.create_table('research_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('project_title', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_histories_id'), 'research_histories', ['id'], unique=False)
    op.create_index(op.f('ix_research_histories_profile_id'), 'research_histories', ['profile_id'], unique=False)
    op.create_table('research_interests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('importance_level', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_interests_id'), 'research_interests', ['id'], unique=False)
    op.create_index(op.f('ix_research_interests_profile_id'), 'research_interests', ['profile_id'], unique=False)
    op.create_table('technology_areas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_areas_id'), 'technology_areas', ['id'], unique=False)
    op.create_index(op.f('ix_technology_areas_name'), 'technology_areas', ['name'], unique=False)
    op.create_index(op.f('ix_technology_areas_profile_id'), 'technology_areas', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_technology_areas_profile_id'), table_name='technology_areas')
    op.drop_index(op.f('ix_technology_areas_name'), table_name='technology_areas')
    op.drop_index(op.f('ix_technology_areas_id'), table_name='technology_areas')
    op.drop_table('technology_areas')
    op.drop_index(op.f('ix_research_interests_profile_id'), table_name='research_interests')
    op.drop_index(op.f('ix_research_interests_id'), table_name='research_interests')
    op.drop_table('research_interests')
    op.drop_index(op.f('ix_research_histories_profile_id'), table_name='research_histories')
    op.drop_index(op.f('ix_research_histories_id'), table_name='research_histories')
    op.drop_table('research_histories')
    op.drop_index(op.f('ix_profile_keywords_profile_id'), table_name='profile_keywords')
    op.drop_index(op.f('ix_profile_keywords_keyword'), table_name='profile_keywords')
    op.drop_index(op.f('ix_profile_keywords_id'), table_name='profile_keywords')
    op.drop_table('profile_keywords')
    op.drop_table('profile_domains')
    op.drop_index(op.f('ix_academic_histories_profile_id'), table_name='academic_histories')
    op.drop_index(op.f('ix_academic_histories_id'), table_name='academic_histories')
    op.drop_table('academic_histories')
    op.drop_index(op.f('ix_research_domains_name'), table_name='research_domains')
    op.drop_index(op.f('ix_research_domains_id'), table_name='research_domains')
    op.drop_table('research_domains')
    # ### end Alembic commands ###
