"""add_user_phone_and_profile_designation_country

Revision ID: 244ef6c34a82
Revises: f8e9f392e6c3
Create Date: 2026-08-25 23:34:33.401307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244ef6c34a82'
down_revision: Union[str, None] = 'f8e9f392e6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('designation', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('profiles', 'country')
    op.drop_column('profiles', 'designation')
    # ### end Alembic commands ###
