"""Add Phase 2B publications and keywords tables

Revision ID: 53d7c57aa26c
Revises: 68afbe48340e
Create Date: 2026-08-25 00:38:48.570784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d7c57aa26c'
down_revision: Union[str, None] = '68afbe48340e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=False),
    sa.Column('primary_domain', sa.String(length=150), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publications_citation_count'), 'publications', ['citation_count'], unique=False)
    op.create_index(op.f('ix_publications_doi'), 'publications', ['doi'], unique=True)
    op.create_index(op.f('ix_publications_external_id'), 'publications', ['external_id'], unique=False)
    op.create_index(op.f('ix_publications_id'), 'publications', ['id'], unique=False)
    op.create_index(op.f('ix_publications_primary_domain'), 'publications', ['primary_domain'], unique=False)
    op.create_index(op.f('ix_publications_publication_date'), 'publications', ['publication_date'], unique=False)
    op.create_index(op.f('ix_publications_source'), 'publications', ['source'], unique=False)
    op.create_index(op.f('ix_publications_title'), 'publications', ['title'], unique=False)
    op.create_index(op.f('ix_publications_venue'), 'publications', ['venue'], unique=False)
    op.create_table('publication_keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_keywords_id'), 'publication_keywords', ['id'], unique=False)
    op.create_index(op.f('ix_publication_keywords_keyword'), 'publication_keywords', ['keyword'], unique=False)
    op.create_index(op.f('ix_publication_keywords_publication_id'), 'publication_keywords', ['publication_id'], unique=False)
    op.create_table('profile_publications',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('publication_id', sa.Integer(), nullable=False),
    sa.Column('is_primary_author', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'publication_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_publications')
    op.drop_index(op.f('ix_publication_keywords_publication_id'), table_name='publication_keywords')
    op.drop_index(op.f('ix_publication_keywords_keyword'), table_name='publication_keywords')
    op.drop_index(op.f('ix_publication_keywords_id'), table_name='publication_keywords')
    op.drop_table('publication_keywords')
    op.drop_index(op.f('ix_publications_venue'), table_name='publications')
    op.drop_index(op.f('ix_publications_title'), table_name='publications')
    op.drop_index(op.f('ix_publications_source'), table_name='publications')
    op.drop_index(op.f('ix_publications_publication_date'), table_name='publications')
    op.drop_index(op.f('ix_publications_primary_domain'), table_name='publications')
    op.drop_index(op.f('ix_publications_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_external_id'), table_name='publications')
    op.drop_index(op.f('ix_publications_doi'), table_name='publications')
    op.drop_index(op.f('ix_publications_citation_count'), table_name='publications')
    op.drop_table('publications')
    # ### end Alembic commands ###
